# Generated by Django 3.2.2 on 2021-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('usermail', models.EmailField(max_length=254)),
                ('userpassword1', models.CharField(max_length=254)),
                ('userpassword2', models.CharField(max_length=254)),
            ],
        ),
    ]
