# Generated by Django 3.2.2 on 2021-08-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
