# Generated by Django 3.2.2 on 2021-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamePost', models.CharField(max_length=100)),
                ('TextPost', models.CharField(max_length=2000)),
                ('ConfirmId', models.CharField(max_length=15)),
            ],
        ),
    ]
