# Generated by Django 3.2.2 on 2021-08-12 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postik', '0002_confirmmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='DatePost',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
